### ISSUE TITLE
"home_path" parameter gives wrong relative path on Windows OS

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Agent-Windows#9]
Hello,

I have a game server (7 Days to Die) where we have to set the relative path of the save game folder. It works fine on Linux, but not on Windows. I guess there is a bug with that.
I use this in the "replace_texts":

```
    <text key="home_path">
      <default>(.*)(property\s+name=&quot;SaveGameFolder&quot;\s+value=&quot;)(.*)(&quot;)(.*&gt;)(.*&lt;.*&gt;.*)</default>
      <var>  &lt;${2}%key%/Saves${4}/&gt;${6}</var>
      <filepath>serverconfig.xml</filepath>
      <options>key-regex</options>
```
So on Linux I get a correct relative path back in the config file. For example:
`  <property name="SaveGameFolder"      value="/home/ogp_agent/OGP_User_Files/43/Saves"/>	<!-- use this to override the default save game path -->`

On Windows I get a wrong relative path back in the config file. For example:
`  <property name="SaveGameFolder"      value="/home/cyg_server/OGP_User_Files/1/Saves"/>	<!-- use this to override the default save game path -->`

The OGP Agent 64 bit installed to C:\OGP64 and the correct relative path should be "C:\OGP64/home/cyg_server/OGP_User_Files/1/Saves"/" I guess. If it is right, then the beginning of the "home_path" missing the relative path of the installed Agent.

If I fix the relative path manually to the correct one which is "C:\OGP64/home/cyg_server/OGP_User_Files/1/Saves" then it works how it should, without it it uses "C:\home/cyg_server/OGP_User_Files/1/Saves" only which is wrong.

**Comment by Adjokip** [comment]
With `C:\OGP64/home/cyg_server/OGP_User_Files/1/Saves` it uses that directory for you?

If I remove the replace text, then regardless of what I have for the value of SaveGameFolder, the server attempts to use `C:\7DaysToDie` or `C:\Users\TEMP\AppData\Roaming\7DaysToDie` ... it seems to change when restarting the VM.

Anyway, the change would probably need to be made in modules/gamemanager/cfg_text_replace.php. [This gist](https://gist.github.com/Adjokip/a9414e508bee6027c68bc7045a6fa4b8) produces the value for `SaveGameFolder` that you want.

Since I seemingly have another issue mentioned above I can't verify if the gist works... but it does place the correct path you mentioned into serverconfig.xml - so feel free to test it.

**Comment by rocco27** [comment]
If I remove "home_path", then the save game folder created out of the game server folder. (same experience on Linux). If I remember "Save" folder was not in the C:\, so probably it was in C:\Users\Profile\AppData\Roaming\7DaysToDie.

Which gist produces exactly the value?

**Comment by Adjokip** [comment]
The 'This gist' part is a link :P

https://gist.github.com/Adjokip/a9414e508bee6027c68bc7045a6fa4b8

For me it'll produce: `<property name="SaveGameFolder" value="C:\OGP64/home/cyg_server/OGP_User_Files/29/Saves"/>`

**Comment by rocco27** [comment]
Oh yeah, I got it and tested. Your patch is perfect! Thank you!

If you pull this patch, then we can close this issue.
